name: Create Post
on:
  workflow_dispatch:
    inputs:
      title:
        description: 'Insert the new post title'     
        required: true

jobs:
  create_post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: sh create-note.sh

      - uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: "feat: create post ${{ inputs.title }}"
