# on:
#   push:
#     branches:
#       - main
name: Deploy to Github Pages
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Checkout
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3.0.11
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Build
        run: |
          npm run build:static
          touch out/.nojekyll
          echo "garrit.xyz" > CNAME
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: out
